{{- if .Values.enableUserServer }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy-user
  labels:
    component: cluster-proxy-user
spec:
  selector:
    open-cluster-management.io/addon: cluster-proxy
    component: cluster-proxy-user
  ports:
    - name: https
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
{{- end }}
